import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";

const inter = Nunito({ subsets: ["latin"], weight: ["1000","200", "300", "400", "500", "600", "700", "800", "900"]});

import ConvexClientProvider from "@/components/convex-client-provider";
import { Toaster } from "sonner";
import { ModalProvider } from "@/components/provider/modal-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    href: "/logo-1.png",
    icon: "/logo-1.png"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ConvexClientProvider>
          <Toaster />
          <ModalProvider />
          {children}
        </ConvexClientProvider>
      </body>
    </html>
  );
}
